rvm:
  - 1.9.3
  - 2.0.0
  - ree
  - rbx-19mode
  - rbx-20mode
  - jruby-19mode
  - jruby-20mode

script: "bundle exec rake spec cucumber"

gemfile:
  - gemfiles/4.0.Gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/3.1.Gemfile
  
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-20mode