rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby

script: "bundle install && bundle exec rake spec cucumber"

gemfile:
  - Gemfile
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile

matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby