# This file was generated by Appraisal

source "http://rubygems.org"

gem "sqlite3", :platform=>:ruby
gem "activerecord-jdbc-adapter", :platform=>:jruby
gem "activerecord-jdbcsqlite3-adapter", :platform=>:jruby
gem "jdbc-sqlite3", :platform=>:jruby
gem "jruby-openssl", :platform=>:jruby
gem "therubyrhino", :platform=>:jruby
gem "sass-rails", "~> 3.1.0"
gem "rails", "~> 3.0.0"

gemspec :path=>"../"